#!/bin/bash -l

cd 0
for NUM in {001..003}
do
        cd $NUM
        rm CHG* REPORT WAVECAR
        rm qha.e* qha.o* qha.pe* qha.po*
        cd ../
done
cd ../

for MINUS in {1..5} #must be consistent with volumes.sh/directory names
do
        cd $MINUS-
        for NUM in {001..XXX} #number of POSCAR-XXX generated by phonopy
        do
                cd $NUM
                rm CHG* REPORT WAVECAR
                rm *.e* *.o* *.p* 
                cd ../
        done
cd ../

for PLUS in {1..5} #must be consistent with volumes.sh/directory names
do
        cd $PLUS+
        for NUM in {001..XXX} #number of POSCAR-XXX generated by phonopy
        do
                cd $NUM
                rm CHG* REPORT WAVECAR
                rm *.e* *.o* *.p* 
                cd ../
        done
cd ../
done
