#!/bin/bash -l

# cp new INCAR_ph, new KPOINTS_ph, and job script into all directories

cp INCAR_ph KPOINTS_ph myjobfile.job 0

for NUM in {1..5}
do
        cp INCAR_ph KPOINTS_ph myjobfile.job $NUM-
done

for NUM in {1..5}
do
        cp INCAR_ph KPOINTS_ph myjobfile.job $NUM+
done

# regular fd.sh

echo 0
cd 0
for NUM in {001..XXX} #number of POSCAR-XXX generated by phonopy
do
        mkdir $NUM
        cp -r POTCAR ./$NUM/
        cp -r KPOINTS_ph ./$NUM/KPOINTS
        cp -r INCAR_ph ./$NUM/INCAR
        cp POSCAR-$NUM $NUM/POSCAR
        cp myjobfile.job $NUM/
        cd  $NUM
        qsub myjobfile.job
        cd ../
   sleep 1
done
cd ..

for NUM in {1..5} #must be consistent with volumes.sh/directory names
do
        echo $NUM-
        cd $NUM-
        for NUM in {001..003} #number of POSCAR-XXX generated by phonopy
        do
                mkdir $NUM
                cp -r POTCAR ./$NUM/
                cp -r KPOINTS_ph ./$NUM/KPOINTS
                cp -r INCAR_ph ./$NUM/INCAR
                cp POSCAR-$NUM $NUM/POSCAR
                cp myjobfile.job $NUM/
                cd  $NUM
                qsub myjobfile.job
                cd ../
                sleep 1
        done
        cd ../
done

for NUM in {1..5} #must be consistent with volumes.sh/directory names
do
        echo $NUM+
        cd $NUM+
        for NUM in {001..003} #number of POSCAR-XXX generated by phonopy
        do
                mkdir $NUM
                cp -r POTCAR ./$NUM/
                cp -r KPOINTS_ph ./$NUM/KPOINTS
                cp -r INCAR_ph ./$NUM/INCAR
                cp POSCAR-$NUM $NUM/POSCAR
                cp myjobfile.job $NUM/
                cd  $NUM
                qsub myjobfile.job
                cd ../
                sleep 1
        done
        cd ../
done
