#!/bin/bash -l

cp settings.conf 0
cd 0
phonopy -f {001..XXX}/vasprun.xml #must be consistent with the number of POSCAR-XXX generated by phonopy
sleep 1
phonopy -p -s -t settings.conf
cp thermal_properties.yaml ../thermal_properties.yaml-0

cd ../

for MINUS in {1..5} #must be consistent with volumes.sh/directory names
do
        cp settings.conf $MINUS-
        cd $MINUS-
        phonopy -f {001..XXX}/vasprun.xml #must be consistent with the number of POSCAR-XXX generated by phonopy
        sleep 1
        phonopy -p -s -t settings.conf
        cp thermal_properties.yaml ../thermal_properties.yaml--$MINUS
        cd ..
done

for PLUS in {1..5} #must be consistent with volumes.sh/directory names
do
        cp settings.conf $PLUS+
        cd $PLUS+
        phonopy -f {001..XXX}/vasprun.xml #must be consistent with the number of POSCAR-XXX generated by phonopy
        phonopy -p -s -t settings.conf
        cp thermal_properties.yaml ../thermal_properties.yaml-$PLUS
        cd ..
done

phonopy-qha -p -s e-v.dat thermal_properties.yaml-{-{5..1},{0..5}} #must be consistent with volumes.sh/directory names
